USE [QLDatChuyenHangOnl]
GO

-- T2: tương đương với proc View_DoiTac_SanPham
-- Khách hàng xem sản phẩm tại các chi nhánh của đối tác 1
-- Sửa lỗi: Bỏ chế độ read uncommitted
SET TRANSACTION ISOLATION LEVEL READ COMMITTED
GO

DECLARE @MaDoiTac INT = 1
BEGIN TRAN
	SELECT SP.MASANPHAM, SP.TENSANPHAM, SP.GIASANPHAM, CN_SP.SOLUONGTON, CN.MACHINHANH
	FROM CHINHANH CN, CHINHANH_SANPHAM CN_SP, SANPHAM SP
	WHERE 
		CN.MADOITAC = @MaDoiTac and
		CN_SP.MACHINHANH = CN.MACHINHANH AND
		CN_SP.MASANPHAM = SP.MASANPHAM AND
		CN_SP.SOLUONGTON <> 0
COMMIT TRAN
GO