USE [QLDatChuyenHangOnl]
GO

-- Tài xế xem đơn hàng đã giao (Chỉ thấy được những đơn hàng 'Đã nhận' của Tài xế này)

SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
GO

DECLARE @MaTaiXe INT = 1
DECLARE @MaDonHang INT = 5
GO

BEGIN TRAN
	UPDATE DONHANG
	SET TINHTRANGDONHANG='Đã nhận'
	WHERE MADONHANG=@MaDonHang AND MATAIXE=@MaTaiXe AND TINHTRANGDONHANG=N'Đang giao'

	WAITFOR DELAY '00:00:05';
ROLLBACK TRAN
GO

BEGIN TRAN
	IF @MaTaiXe IS NULL OR NOT EXISTS ( SELECT MATAIXE FROM TAIXE )
	BEGIN
		RAISERROR (N'Mã tài xế không hợp lệ.', -1, -1)
		ROLLBACK TRAN
		RETURN 
	END

	SELECT MADONHANG, NGAYLAP, PHIVANCHUYEN
	FROM DONHANG
	WHERE MATAIXE=@MaTaiXe AND TINHTRANGDONHANG=N'Đã nhận'
COMMIT TRAN
GO
-- Tài xế vẫn thấy Mã đơn hàng 5 dù tình trạng đơn hàng = 'Đang giao'